### ISSUE TITLE
Quest Guardians of Hyjal: Call of the Ancients

### ISSUE THREAD

**Issue by Teokharis** [BurnedLand/Reports#25]
**[Orso, Horde]** 

**[Guardians of Hyjal: Call of the Ancients]**

**[Tortolla and Aessina don't spawn at their place]** 

**[]**

**[none]**

**Comment by Maze003** [comment]
Questo problema arriva dalla versione precedente, dove a causa un bug non veniva contato il "assisted credit" per Tortolla e Aessina. Adesso invece con un nuovo personaggio sembra completabile. Appena ti trovo in game ti completo la quest. Grazie del report :) @Teokharis
