### ISSUE TITLE
Quest The Call of the World-Shaman

### ISSUE THREAD

**Issue by Teokharis** [BurnedLand/Reports#27]
**[Orso, Horde]** 

**[The Call of the World-Shaman,Quest]**

**[Thrall doesn't Spawn at his place]** 

**[]**

**[none]**

**Comment by Maze003** [comment]
Tutta la quest che vegono dopo di questa non funzionano correttamente, per quello che la quest non si poteva consegnare. Sistemarle sembra richiedere più del previsto.
Nel mentre ho pubblicato un temp fix, che permette di terminare la questchain ed ottenere la ricompensa di quest'ultima.
