### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rajha93** [BurnedLand/Reports#36]
"Player Name and Faction"= rajha, ally

"Type and Name"= zona iniziale worghen

"Describe the bug"=barre del pet del hunter inesistenti, ho controllato fino al liv 15

"Wowhead link"=

"Screenshots"=

**Comment by Maze003** [comment]
@Rajha93  dovrebbe essere così se non erro.

https://www.engadget.com/2010-04-09-cataclysm-class-changes-hunter.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAADl_9CK1gdqOHZs7koMzUoodQAh_GTIMT3Xd0iVW2xqyIhcvqzpuRPmsDiQxhrTb0lq4AjgzQbBQ36D69ybFLkWt3_DendMHGIJ0W2_V9J6kXOyHNFvfjrVw9nVDIPI_ylNmytQ85K_jbk-ICoNGMD9mkNZ9-f0IdlUVf17zwRVQ

Additionally, hunters will now start with a race-appropriate pet at level 1 and will be able to tame a different pet at level 10
